// export enum RegimeEspecialTributacao {
//   RET_NENHUM
//   RET_MICROEMPRESA_MUNICIPAL
// RET_ESTIMATIVA
// RET_SOCIEDADE_PROFISSIONAIS
// RET_COOPERATIVA
// RET_MICROEMPRESARIO_INDIVIDUAL
// RET_MICROEMPRESARIO_EMPRESA_PP
// RET_EMPRESA_PP
// RET_SIMPLES_NACIONAL
// RET_LUCRO_PRESUMIDO
// RET_LUCRO_REAL
// RET_OUTROS

// // }
// export enum RegimeEspecialTributacao {
//   RET_MICROEMPRESA_MUNICIPAL = 1,
//   RET_ESTIMATIVA = 2,
//   RET_SOCIEDADE_PROFISSIONAIS = 3,
//   RET_COOPERATIVA = 4,
//   RET_MICROEMPRESARIO_INDIVIDUAL = 5,
//   RET_MICROEMPRESARIO_EMPRESA_PP = 6,
//   RET_EMPRESA_PP = 6,
// }
